# EM TaskFlow Development Configuration
# This file contains development-specific overrides

env: "development"

# Development typically uses local services
server:
  host: "127.0.0.1"

# Enable integrations based on available credentials
mcp:
  # In development, integrations are optional and based on env vars
  notion:
    enabled: true   # Enable Notion for testing with provided credentials
  jira:
    enabled: true   # Enable Jira with provided credentials
  google:
    enabled: false  # Set to true in local override if you have credentials

# Development optimizations
rag:
  maxChunkSize: 800  # Smaller chunks for faster processing in development