# EM TaskFlow Local Configuration Example
# Copy this file to local.yml and customize with your API keys and settings
# This file should NOT be committed to version control

# LLM Provider API Keys (uncomment and add your keys)
llm:
  # Uncomment the provider you want to use as primary
  # provider: "openai"  # or "anthropic", "google", "huggingface", "ollama"
  
  openai:
    apiKey: "your-openai-api-key-here"
  
  anthropic:
    apiKey: "your-anthropic-api-key-here"
  
  google:
    apiKey: "your-google-ai-api-key-here"
  
  huggingface:
    apiKey: "your-huggingface-api-key-here"

# MCP Integration Credentials
mcp:
  notion:
    apiKey: "your-notion-integration-api-key"
    enabled: true  # Set to true when you have a valid API key
  
  jira:
    url: "https://your-company.atlassian.net"
    username: "your-email@company.com"
    apiToken: "your-jira-api-token"
    projectKey: "YOUR-PROJECT-KEY"
    enabled: true  # Set to true when you have valid credentials
  
  google:
    oauthCredentials: '{"type":"service_account","project_id":"your-project",...}'
    calendarId: "primary"  # or your specific calendar ID
    enabled: true  # Set to true when you have valid credentials

# Development-specific overrides
server:
  port: 4000  # Change if needed for local development

# Vector database (if running on different host/port)
vectorDb:
  chroma:
    host: "localhost"
    port: 8000

# RAG settings
rag:
  enabled: true
  maxChunkSize: 1000  # Adjust based on your needs